japokwm-output_transform(5)

# Type
	enum Output_transform
# Description
	An enum that 
# Variables
	normal
		The normal transform
	transform_90
		The transform 90
	transform_180
		The transform 180
	transform_270
		The transform 270
	transform_flipped
		The transform flipped
	transform_flipped_90
		The transform flipped 90
	transform_flipped_180
		The transform flipped 180
	transform_flipped_270
		The transform flipped 270
