japokwm-monitor(5)

# Type
	class Monitor
# Description
	The monitor is what the user sees.
# Variables
	float scale = 1.0
		The scale of the monitor.
	Output_transform transform = Output_transform.normal
		The transform of the monitor.
	bool focused = false
		Whether the monitor is focused.
	bool root = current root
		get the root of the monitor.
	Tag tag = current tag
		get the tag of the monitor.
