japokwm-list(5)

# Description
	An immutable list of objects.
# Operators
	a[i]
		Returns the i-th element of the list.
# Methods
	int find(con)
		Finds the index of the container object con in the list.
		Returns -1 if not found.
	int repush(i, j)
		pushes the object at index i into the index j.
	int swap(i, j)
		Swaps the object at index i with the object at index j.
# Variables
	int len
		The length of the list.
